### ISSUE TITLE
Landing page design - sprint 1

### ISSUE THREAD

**Issue by pankaja-shree** [chingu-voyage3/bears-25#1]
complete the landing page according to this design - 
https://xd.adobe.com/spec/06611bd8-a40b-476e-b091-6ced92a67373/#screen/f81c9b88-c16c-4215-bce8-a779a9af904c/Home%20Page

**Comment by pankaja-shree** [comment]
using vuetify

**Comment by Ipaye** [comment]
okay seen :+1: @pankaja-shree

**Comment by pankaja-shree** [comment]
how far has this been done ? Will it be over by this week ?

**Comment by Ipaye** [comment]
sadly no, i didnt think we were continuing with it. and ive been a bit
swammed

Regards,
Ipaye Alameen
Manager: Google Developers Group (GDG)Unilag

**Comment by pankaja-shree** [comment]
its ok. Can it be finished in sprint 2 ?

**Comment by Ipaye** [comment]
yes it can.
i apologies if i am slowing things down

Regards,
Ipaye Alameen
Manager: Google Developers Group (GDG)Unilag

**Comment by pankaja-shree** [comment]
Continued in sprint 2
