### ISSUE TITLE
Unable to push changes

### ISSUE THREAD

**Issue by harshil1712** [chingu-voyage3/bears-25#20]
I created a new branch and when I tried to push the changes it shows an error of permission denied

**Comment by rameshsyn** [comment]
@harshil1712 Oh, Are you added as a collaborator?

**Comment by harshil1712** [comment]
@rameshsyn I am afraid not.

**Comment by rameshsyn** [comment]
You might need to PULL Request the changes, I don't have permission to add a collaborator. @harshil1712

**Comment by harshil1712** [comment]
@rameshsyn for that I will need to be a collaborator. Or else I will have to fork the repo and then work on it, I suppose. @pankaja-shree can you look into this?

**Comment by pankaja-shree** [comment]
I'll add u as collaborator

**Comment by pankaja-shree** [comment]
In the list of contributors I can see only 2 names. How to add both of you ?

**Comment by harshil1712** [comment]
@pankaja-shree @rameshsyn can we continue this discussion over slack?

**Comment by rameshsyn** [comment]
@pankaja-shree In repo settings, there is collaborators tab. 
@harshil1712 Okay but I like GitHub more cuz discussion will be public and accessible anytime. :dancer:

**Comment by harshil1712** [comment]
@rameshsyn agreed. But I thought this issue should not be discussed here much 😅

**Comment by rameshsyn** [comment]
lol Okay

**Comment by tropicalchancer** [comment]
@harshil1712 saw this issue thread and you've been added a collaborator. :)

**Comment by harshil1712** [comment]
@tropicalchancer thank you so much!!!! ❤️

**Comment by rameshsyn** [comment]
@tropicalchancer :handshake:  :wave:  :wave:  :wave:
