### ISSUE TITLE
Complete landing page

### ISSUE THREAD

**Issue by pankaja-shree** [chingu-voyage3/bears-25#8]

**Comment by pankaja-shree** [comment]
Need to footer and stories (cards) display . @harshil1712 will you be able to do this? since you have done most of the landing page coding.
As for the stories - please use this placeholder - https://jsonplaceholder.typicode.com/

**Comment by pankaja-shree** [comment]
@Ipaye Are you completing the landing page? Will it be over by tomorrow?

**Comment by Ipaye** [comment]
It should be. Just having issues making the footer responsive and grid
locking the stories

**Comment by pankaja-shree** [comment]
responsive header  and footer done.
